services:
  guacamole:
    image: jwetzell/guacamole:1.6.0-20260804
    restart: unless-stopped
    volumes:
      - guacamole_config:/config
    environment:
      TZ: Asia/Kolkata

volumes:
  guacamole_config:
